
_vehicle = _this;
_driver = driver _vehicle;
_eng = isengineon _vehicle;
_vehicle setVelocity [0,0,0];

if (_eng) then {
	_vehicle vehicleChat format ["Stop engine in 15s to sell vehicle. You will get 3/4 of the vehicle store price."];
	sleep 15;
	_eng = isengineon _vehicle;
	if (_eng) exitWith {_vehicle vehicleChat format ["Engine still running. Deal CANCELED!"];};
};


if((player == driver _vehicle) && (!_eng))then {
	_type = typeOf _vehicle;
	_playerMoney = player getVariable "cmoney";

	_price = 300;
	if(_type == "C_Kart_01_F") then {_price = 75;};	
	if(_type == "C_Quadbike_01_F") then {_price = 112;};
	if(_type == "B_Quadbike_01_F") then {_price = 150;};
	if(_type == "O_Quadbike_01_F") then {_price = 150;};
	if(_type == "I_Quadbike_01_F") then {_price = 150;};
	if(_type == "B_G_Quadbike_01_F") then {_price = 150;};
	if(_type == "C_Hatchback_01_F") then {_price = 300;};
	if(_type == "C_Hatchback_01_sport_F") then {_price = 525;};
	if(_type == "C_SUV_01_F") then {_price = 562;};
	if(_type == "C_Offroad_01_F") then {_price = 562;};
	if(_type == "B_G_Offroad_01_F") then {_price = 600;};
	if(_type == "B_G_Offroad_01_armed_F") then {_price = 1875;};
	if(_type == "C_Van_01_transport_F") then {_price = 187;};
	if(_type == "B_G_Van_01_transport_F") then {_price = 225;};
	if(_type == "C_Van_01_box_F") then {_price = 225;};
	if(_type == "C_Van_01_fuel_F") then {_price = 1500;};
	if(_type == "B_G_Van_01_fuel_F") then {_price = 1575;};
	if(_type == "B_Truck_01_mover_F") then {_price = 1500;};
	if(_type == "B_Truck_01_box_F") then {_price = 2250;};
	if(_type == "B_Truck_01_transport_F") then {_price = 2250;};
	if(_type == "B_Truck_01_covered_F") then {_price = 3000;};
	if(_type == "B_Truck_01_fuel_F") then {_price = 3750;};
	if(_type == "B_Truck_01_medical_F") then {_price = 4500;};
	if(_type == "B_Truck_01_Repair_F") then {_price = 5625;};
	if(_type == "B_Truck_01_ammo_F") then {_price = 11250;};
	if(_type == "O_Truck_03_device_F") then {_price = 1875;};	
	if(_type == "O_Truck_03_transport_F") then {_price = 2250;};
	if(_type == "O_Truck_03_covered_F") then {_price = 3000;};
	if(_type == "O_Truck_03_fuel_F") then {_price = 3750;};
	if(_type == "O_Truck_03_medical_F") then {_price = 4500;};
	if(_type == "O_Truck_03_repair_F") then {_price = 5625;};
	if(_type == "O_Truck_03_ammo_F") then {_price = 11250;};
	if(_type == "I_Truck_02_transport_F") then {_price = 1500;};
	if(_type == "I_Truck_02_covered_F") then {_price = 2250;};
	if(_type == "I_Truck_02_fuel_F") then {_price = 3000;};
	if(_type == "I_Truck_02_medical_F") then {_price = 4500;};
	if(_type == "I_Truck_02_box_F") then {_price = 5250;};
	if(_type == "I_Truck_02_ammo_F") then {_price = 10500;};
	if(_type == "B_MRAP_01_F") then {_price = 1500;};
	if(_type == "B_MRAP_01_hmg_F") then {_price = 6000;};
	if(_type == "B_MRAP_01_gmg_F") then {_price = 7500;};
	if(_type == "O_MRAP_02_F") then {_price = 1500;};
	if(_type == "O_MRAP_02_hmg_F") then {_price = 6000;};
	if(_type == "O_MRAP_02_gmg_F") then {_price = 7500;};
	if(_type == "I_MRAP_03_F") then {_price = 1500;};
	if(_type == "I_MRAP_03_hmg_F") then {_price = 6000;};
	if(_type == "I_MRAP_03_gmg_F") then {_price = 7500;};
	if(_type == "O_APC_Wheeled_02_rcws_F") then {_price = 9375;};
	if(_type == "B_APC_Wheeled_01_cannon_F") then {_price = 11250;};
	if(_type == "I_APC_Wheeled_03_cannon_F") then {_price = 13125;};
	if(_type == "B_APC_Tracked_01_CRV_F") then {_price = 12000;};	
	if(_type == "B_APC_Tracked_01_rcws_F") then {_price = 13500;};
	if(_type == "I_APC_tracked_03_cannon_F") then {_price = 14250;};
	if(_type == "O_APC_Tracked_02_cannon_F") then {_price = 15000;};
	if(_type == "B_APC_Tracked_01_AA_F") then {_price = 15000;};
	if(_type == "O_APC_Tracked_02_AA_F") then {_price = 15000;};
	if(_type == "B_MBT_01_cannon_F") then {_price = 18750;};
	if(_type == "B_MBT_01_TUSK_F") then {_price = 18750;};
	if(_type == "O_MBT_02_cannon_F") then {_price = 18750;};
	if(_type == "I_MBT_03_cannon_F") then {_price = 18750;};
	if(_type == "B_Heli_Light_01_F") then {_price = 2250;};
	if(_type == "O_Heli_Light_02_unarmed_F") then {_price = 3375;};
	if(_type == "I_Heli_light_03_unarmed_F") then {_price = 3375;};
	if(_type == "I_Heli_Transport_02_F") then {_price = 5625;};
	if(_type == "B_Heli_Transport_01_F") then {_price = 11250;};
	if(_type == "B_Heli_Transport_01_camo_F") then {_price = 12000;};
	if(_type == "B_Heli_Light_01_armed_F") then {_price = 15000;};
	if(_type == "O_Heli_Light_02_F") then {_price = 15000;};
	if(_type == "I_Heli_light_03_F") then {_price = 16875;};
	if(_type == "B_Heli_Attack_01_F") then {_price = 20625;};
	if(_type == "O_Heli_Attack_02_F") then {_price = 22500;};
	if(_type == "O_Heli_Attack_02_black_F") then {_price = 22500;};
	if(_type == "I_Plane_Fighter_03_AA_F") then {_price = 15000;};
	if(_type == "I_Plane_Fighter_03_CAS_F") then {_price = 18750;};
	if(_type == "B_Plane_CAS_01_F") then {_price = 22500;};
	if(_type == "O_Plane_CAS_02_F") then {_price = 22500;};	
	if(_type == "C_Rubberboat") then {_price = 75;};
	if(_type == "B_Lifeboat") then {_price = 75;};
	if(_type == "O_Lifeboat") then {_price = 75;};
	if(_type == "B_Boat_Transport_01_F") then {_price = 112;};
	if(_type == "O_Boat_Transport_01_F") then {_price = 112;};
	if(_type == "I_Boat_Transport_01_F") then {_price = 112;};
	if(_type == "B_G_Boat_Transport_01_F") then {_price = 112;};
	if(_type == "C_Boat_Civil_01_F") then {_price = 300;};
	if(_type == "C_Boat_Civil_rescue_01_F") then {_price = 300;};
	if(_type == "C_Boat_Civil_police_01_F") then {_price = 337;};
	if(_type == "O_Boat_Armed_01_hmg_F") then {_price = 3000;};
	if(_type == "B_Boat_Armed_01_minigun_F") then {_price = 3000;};
	if(_type == "I_Boat_Armed_01_minigun_F") then {_price = 3000;};
	if(_type == "B_SDV_01_F") then {_price = 375;};
	if(_type == "O_SDV_01_F") then {_price = 375;};
	if(_type == "I_SDV_01_F") then {_price = 375;};

		player setVariable["cmoney",(player getVariable "cmoney")+_price,true];
		player setVariable["timesync",(player getVariable "timesync")+(_price * 3),true];
		[] call fn_savePlayerData;
		["Dismantling will take about 1 minute.", 10] call mf_notify_client;
		
		_vehicle setFuel 0;
		_vehicle setVelocity [0,0,0];
		_text = format ["Selling %1 for $%2. Removing Engine, emptying fluids, and removing ammo.", _type, _price];
		[_text, 5] call mf_notify_client;
		sleep 5;
		["Chopping up vehicle.", 5] call mf_notify_client;
		_this animate ["HideBackpacks", 1];
		sleep 1;
		_this animate ["HideBumper1", 1];
		sleep 1;
		_this animate ["HideBumper2", 1];
		sleep 1;
		_this animate ["HideDoor1", 1];
		sleep 1;		
		_this animate ["HideDoor2", 1];
		sleep 1;
		_this animate ["HideDoor3", 1];
		sleep 1;
		deleteVehicle _this;

		_text = format ["%1 has been chopped.", _type];
		[_text, 10] call mf_notify_client;
		if (true) exitWith {};
	};
